## YAML Template.


server:
    port: 9191
    
spring:
    jpa:
        hibernate:
            ddl-auto: update
    sql:
        init:
            platform: h2
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:~/orderdb
        
    application:
        name: ORDER-SERVICE     
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url: 
            defaultzone: http://localhost:8761/eureka/
    instance:
        hostname: localhost 
        
        
        
